sudo: false
language: erlang
otp_release:
  - 21.0.2
  - 20.3
  - 19.3
cache:
  directories:
  - $HOME/otp/19.1
  - $HOME/otp/19.2
  - $HOME/.cache/rebar3
  - _plt
install: "true"
script: "make travis"
branches:
  only:
    - master
    - develop
notifications:
  email:
    - pj@ezgr.net

